### ISSUE TITLE
Error retrieving credentials

### ISSUE THREAD

**Issue by euhruska** [cedadev/MyProxyClient#13]
I get an error a below when running bootstrap and having the certificates in the same directory and set $X509_USER_PROXY to this directory.
```Error retrieving credentials: Loading certificate and private key for SSL connection [also check CA certificate settings]: Traceback (most recent call last):
  File "/scratch1/eh22/conda/lib/python3.6/site-packages/myproxy/client.py", line 762, in _initConnection
    context.use_certificate_chain_file(certFile)
  File "/scratch1/eh22/conda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 887, in use_certificate_chain_file
    _raise_current_error()
  File "/scratch1/eh22/conda/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_certificate_chain_file', 'PEM lib')]```

**Comment by philipkershaw** [comment]
You should set `$X509_USER_PROXY` to a file containing the user certificate and private key rather than setting it to a directory.
