### ISSUE TITLE
SSL3_GET_RECORD 'wrong version number

### ISSUE THREAD

**Issue by gerbier** [cedadev/MyProxyClient#15]
I am using myproxyclient (2.0.1) since some years to get credentials for CMIP project data.
Today, the command fails with the following error :

$ myproxyclient logon -s esgf-node.ipsl.upmc.fr -p 7512 -l gerbier -o gerbier.cred
Enter password for user 'gerbier' on MyProxy server 'esgf-node.ipsl.upmc.fr':
Traceback (most recent call last):
  File "/usr/bin/myproxyclient", line 9, in <module>
    load_entry_point('MyProxyClient==2.0.1', 'console_scripts', 'myproxyclient')()
  File "/usr/lib/python2.7/site-packages/MyProxyClient-2.0.1-py2.7.egg/myproxy/script.py", line 196, in main
    do_logon(myproxy, options)
  File "/usr/lib/python2.7/site-packages/MyProxyClient-2.0.1-py2.7.egg/myproxy/script.py", line 221, in do_logon
    updateTrustRoots=options.trustroots)
  File "/usr/lib/python2.7/site-packages/MyProxyClient-2.0.1-py2.7.egg/myproxy/client.py", line 1498, in logon
    conn.write(self.__class__.GLOBUS_INIT_MSG)
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1254, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1172, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')]

I have tested the same account , with myproxy-logon, and with the java client (http://grid.ncsa.illinois.edu/myproxy/MyProxyLogon/) and this 2 tools are still working.

Can you help me ?

**Comment by cehbrecht** [comment]
@gerbier see #14.

**Comment by gerbier** [comment]
thank you, the 2.0.3 release fixes the problem !
